### ISSUE TITLE
[FEATURE] Synchronize project translations with Crowdin

### ISSUE THREAD

**Issue by AmadeusGraves** [stumpapp/stump#139]
**Is your feature request related to a problem? Please describe.**
Right now to translate the project you have to handle the translation files directly and compare them to check for missing fields, which makes the work difficult.

**Describe the solution you'd like**
Translations can be synchronized with Crowdin, which is a platform that automates translations, i.e. if a new field is entered in the English translation file, Crowdin will add it to the other files.

In addition, the translator does not have to touch any file in github, they only has to access the Crowdin website and translate, which also helps to ensure that the files are always correct.

**Describe alternatives you've considered**
Also, exists Weblate. 

**Additional context**
Here's the doc to configure Crowdin with github: https://support.crowdin.com/github-integration/

**Comment by aaronleopold** [comment]
> 60,000 hosted words

So this _seems_ like it should be enough. Stump's incomplete english set has around ~650 words. I'm going to arbitrarily guess I'll need at least 1000 for a complete set. So, it would then be a total of 1000 * X, where X is how ever many languages to translate. After which, it is minimum of $50/mo, which is definitely way more than I will spend out of pocket.

Weblate seems to have a completely free, self-hosted option which is very fitting for this space 😄. However, having taken a look at the setup docs, I probably won't have time in the immediate future to do that much. So Crowdin is definitely seemingly the quicker route.

If you have any interest in doing work towards either of these integrations, I would lean towards help configure weblate, since a portable Docker setup could probably be done and then hosted on my GitHub runner machine. Regardless, I'll consider both options. Thanks for submitting the ticket!

**Comment by andrii-bodnar** [comment]
Hi there, Crowdin is [free for open-source](https://crowdin.com/page/open-source-project-setup-request) projects by the way 🙂

**Comment by aaronleopold** [comment]
> Hi there, Crowdin is [free for open-source](https://crowdin.com/page/open-source-project-setup-request) projects by the way 🙂

Hell yeah, I completely missed that section! Thank you, I'll fill out the form 👍

**Comment by aaronleopold** [comment]
https://crowdin.com/project/stump

**Comment by AmadeusGraves** [comment]
@aaronleopold you're welcome! I'll start translating the project.
